spring:
  application:
    name: system
  #数据库连接
  datasource:
    url: jdbc:mysql://localhost:33060/studyvideo?characterEncoding=UTF8&autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 9001
eureka:
  client:
    service-url:
    #注册中心的地址
      defaultZone: http://localhost:8761/eureka
#mybatis 配置
mybatis:
  mapper-locations: classpath:com/example/system/Dao/mapper/*.xml
  type-aliases-package: com.example.system.entity
